### ISSUE TITLE
Precomputing  messageblocks

### ISSUE THREAD

**Issue by automatonical** [ctz/fastpbkdf2#12]
From the paper [On the weakness of PBKDF2](https://www.researchgate.net/profile/Andrea_Visconti/publication/297734021_On_the_weaknesses_of_PBKDF2/links/56e1ce9b08ae4e3e94281b44/On-the-weaknesses-of-PBKDF2.pdf]), it's possible to speed up by 50% if the first block is precomputed. Read the [strategies](https://jbp.io/2015/08/11/pbkdf2-performance-matters.html#strategies) you used, doesn't look like this is mentioned.

**Comment by ctz** [comment]
From my blog post:

> The PBKDF2 standards describe the algorithm in such an unhelpful way that almost every defender implementation is at least two times slower than it otherwise could be.

This is talking about the same lack of precomputation.

My 2015 slides for that talk have, I think at least, clearer diagrams describing the precomputation than the 2016 paper.
