### ISSUE TITLE
Cut a release for fastpbkdf2

### ISSUE THREAD

**Issue by Ayrx** [ctz/fastpbkdf2#3]
Hey, do you mind tagging a release whenever there are any useful updates to fastpbkdf2? Would make it easier for me to know when I need to cut a new release for the Python bindings.

**Comment by ctz** [comment]
I've made v1.0.0. No interesting changes, but I'll adopt semver for any future changes relative to this starting point.

**Comment by Ayrx** [comment]
Thank you!
